### ISSUE TITLE
iOS での動画再生中の回転制御問題。

### ISSUE THREAD

**Issue by im-kashi** [imobile-maio/maio-Cocos2d-x-Plugin#1]
iOS で広告動画を再生中に端末をローテーションさせると、意図したものとは異なる回転アニメーションがなされる場合がある。

**Comment by im-ttmskk** [comment]
- 発生頻度
    - ごくまれ
- 再現手順
    - 不明

追加の情報を募集しています。

**Comment by ghost** [comment]
iOSの表示ロジックの変更後、及びcocos2d-xプラグインv1.0.0リリース後から特に報告が無いため一旦クローズします。
